/**
 * SQL Queries for Order Operations (ITM Database)
 * Extracted from Node-RED flows.json
 */

export const OrdersQueries = {
  // Base query to get orders with all joins
  getOrdersBase: (extraCondition?: string) => `
    SELECT DISTINCT O.ID, O.ITM_ORDERNUM, O.ORDERNUM, O.ORDER_TYPE, O.MANAGER, 
           C.CLIENTNAME, C.CITY, C.PRICE_COLUMN,
           O.FASAD_MAT, O.FASAD_MODEL, O.COLOR, O.ORDER_TOTAL_COST, O.ORDER_COST, O.ORDER_PAY,
           (O.ORDER_TOTAL_COST - COALESCE(O.ORDER_PAY, 0)) * -1 AS ORDER_DEBT, 
           O.ORDER_GENERALSQ,
           O.FACT_DATE_FIRSTSAVE, O.PLAN_DATE_FIRSTSTAGE, O.PLAN_DATE_PACK, O.FACT_DATE_ORDER_OUT,
           LIST_STATUSES.STATUS_DESCRIPTION, LIST_STATUSES.STATUS_NUM, 
           O.FACT_DATE_FIRSTSAVE, C.IS_PREPAID,
           O.COLOR_TYPE, O.COLOR_PATINA, O.PRIMECH
    FROM ORDERS O
    LEFT JOIN CLIENTS C ON O.CLIENT = C.CLIENTNAME
    LEFT JOIN LIST_STATUSES ON LIST_STATUSES.STATUS_NUM = O.ORDER_STATUS
    WHERE O.ORDER_STATUS > -3 ${extraCondition ? 'AND ' + extraCondition : ''}
    ORDER BY O.ID DESC
  `,

  // Get orders with element details
  getOrdersWithElements: (extraCondition?: string) => `
    SELECT DISTINCT O.ID, O.ITM_ORDERNUM, O.ORDERNUM, O.ORDER_TYPE, O.MANAGER, 
           C.CLIENTNAME, C.CITY, C.PRICE_COLUMN,
           O.FASAD_MAT, O.FASAD_MODEL, O.COLOR, O.ORDER_TOTAL_COST, O.ORDER_COST, O.ORDER_PAY,
           (O.ORDER_TOTAL_COST - COALESCE(O.ORDER_PAY, 0)) * -1 AS ORDER_DEBT, 
           O.ORDER_GENERALSQ,
           O.FACT_DATE_FIRSTSAVE, O.PLAN_DATE_FIRSTSTAGE, O.PLAN_DATE_PACK, O.FACT_DATE_ORDER_OUT,
           LIST_STATUSES.STATUS_DESCRIPTION, LIST_STATUSES.STATUS_NUM, 
           O.FACT_DATE_FIRSTSAVE, C.IS_PREPAID,
           O.COLOR_TYPE, O.COLOR_PATINA, O.PRIMECH  
    FROM ORDERS O
    LEFT JOIN CLIENTS C ON O.CLIENT = C.CLIENTNAME
    LEFT JOIN LIST_STATUSES ON LIST_STATUSES.STATUS_NUM = O.ORDER_STATUS
    LEFT JOIN ORDERS_ELEMENTS L ON (L.ORDER_ID = O.ID)
    WHERE O.ORDER_STATUS > -3 ${extraCondition ? 'AND ' + extraCondition : ''}
    ORDER BY O.ID DESC
  `,

  // Get single order by ID with full details
  getOrderById: (orderId: number) => `
    SELECT * 
    FROM ORDERS O 
    LEFT JOIN LIST_STATUSES S ON (S.STATUS_NUM = O.ORDER_STATUS) 
    WHERE O.ID = ${orderId}
  `,

  // Get order elements (nomenclatures)
  getOrderElements: (orderId: number) => `
    SELECT * 
    FROM ORDERS_ELEMENTS L 
    WHERE L.ORDER_ID = ${orderId}
  `,

  // Get order plans
  getOrderPlans: (orderId: number) => `
    SELECT * 
    FROM orders_date_plan p 
    WHERE p.order_id = ${orderId} 
    ORDER BY p.date3, p.id
  `,

  // Get order execution plan (stages: shlif, lack, upack, out)
  getOrderExecutionPlan: (orderId: number) => `
    SELECT O.ID,
           JS.DATE_GEN_ORDER_END AS SHLIF_DATE, JS.FREEZE_FLAG AS SHLIF_FREEZE_FLAG, JS.comment AS SHLIF_COMMENT,
           JL.lack_date AS LACK_DATE, jl.freeze_flag AS LACK_FREEZE_FLAG, JL.COMMENT AS LACK_COMMENT,
           JU.date_pack AS UPACK_DATE, JO.pack_type, JO.fact_date_out
    FROM ORDERS O
    LEFT JOIN JOURNAL_LACK JL ON (JL.ORDER_ID = O.ID)
    LEFT JOIN JOURNAL_SHLIF JS ON (JS.ORDER_ID = O.ID)
    LEFT JOIN JOURNAL_UPACK JU ON (JU.ORDER_ID = O.ID)
    LEFT JOIN JOURNAL_OUT JO ON (JO.ORDER_ID = O.ID)
    WHERE O.ID = ${orderId}
  `,

  // Get recent actions with order
  getRecentOrderActions: (orderId: number) => `
    SELECT FIRST 10 S.MANAGER, S.DESCRIPTION 
    FROM ORDER_STATUSES S 
    WHERE S.ORDER_ID = ${orderId} 
    ORDER BY S.TIME_STAMP DESC
  `,

  // Get manager's orders
  getOrdersByManager: (managerName: string) => `
    SELECT DISTINCT O.ID, O.ITM_ORDERNUM, O.ORDERNUM, O.ORDER_TYPE, O.MANAGER, 
           C.CLIENTNAME, C.CITY, C.PRICE_COLUMN,
           O.FASAD_MAT, O.FASAD_MODEL, O.COLOR, O.ORDER_TOTAL_COST, O.ORDER_COST, O.ORDER_PAY,
           (O.ORDER_TOTAL_COST - COALESCE(O.ORDER_PAY, 0)) * -1 AS ORDER_DEBT, 
           O.ORDER_GENERALSQ,
           O.FACT_DATE_FIRSTSAVE, O.PLAN_DATE_FIRSTSTAGE, O.PLAN_DATE_PACK, O.FACT_DATE_ORDER_OUT,
           LIST_STATUSES.STATUS_DESCRIPTION, LIST_STATUSES.STATUS_NUM, 
           C.IS_PREPAID, O.COLOR_TYPE, O.COLOR_PATINA, O.PRIMECH
    FROM ORDERS O
    LEFT JOIN CLIENTS C ON O.CLIENT = C.CLIENTNAME
    LEFT JOIN LIST_STATUSES ON LIST_STATUSES.STATUS_NUM = O.ORDER_STATUS
    WHERE O.ORDER_STATUS > -3 AND UPPER(O.MANAGER) LIKE '%${managerName.toUpperCase()}%'
    ORDER BY O.ID DESC
  `,

  // Get packaged orders
  getPackagedOrders: () => `
    SELECT DISTINCT O.ID, O.ITM_ORDERNUM, O.ORDERNUM, O.ORDER_TYPE, O.MANAGER, 
           C.CLIENTNAME, C.CITY, C.PRICE_COLUMN,
           O.FASAD_MAT, O.FASAD_MODEL, O.COLOR, O.ORDER_TOTAL_COST, O.ORDER_COST, O.ORDER_PAY,
           (O.ORDER_TOTAL_COST - COALESCE(O.ORDER_PAY, 0)) * -1 AS ORDER_DEBT, 
           O.ORDER_GENERALSQ,
           O.FACT_DATE_FIRSTSAVE, O.PLAN_DATE_FIRSTSTAGE, O.PLAN_DATE_PACK, O.FACT_DATE_ORDER_OUT,
           LIST_STATUSES.STATUS_DESCRIPTION, LIST_STATUSES.STATUS_NUM, 
           C.IS_PREPAID, O.COLOR_TYPE, O.COLOR_PATINA, O.PRIMECH
    FROM ORDERS O
    LEFT JOIN CLIENTS C ON O.CLIENT = C.CLIENTNAME
    LEFT JOIN LIST_STATUSES ON LIST_STATUSES.STATUS_NUM = O.ORDER_STATUS
    WHERE O.ORDER_STATUS > -3 AND O.ORDER_STATUS = 8
    ORDER BY O.ID DESC
  `,

  // Get packaged orders with debt
  getPackagedOrdersWithDebt: () => `
    SELECT DISTINCT O.ID, O.ITM_ORDERNUM, O.ORDERNUM, O.ORDER_TYPE, O.MANAGER, 
           C.CLIENTNAME, C.CITY, C.PRICE_COLUMN,
           O.FASAD_MAT, O.FASAD_MODEL, O.COLOR, O.ORDER_TOTAL_COST, O.ORDER_COST, O.ORDER_PAY,
           (O.ORDER_TOTAL_COST - COALESCE(O.ORDER_PAY, 0)) * -1 AS ORDER_DEBT, 
           O.ORDER_GENERALSQ,
           O.FACT_DATE_FIRSTSAVE, O.PLAN_DATE_FIRSTSTAGE, O.PLAN_DATE_PACK, O.FACT_DATE_ORDER_OUT,
           LIST_STATUSES.STATUS_DESCRIPTION, LIST_STATUSES.STATUS_NUM, 
           C.IS_PREPAID, O.COLOR_TYPE, O.COLOR_PATINA, O.PRIMECH
    FROM ORDERS O
    LEFT JOIN CLIENTS C ON O.CLIENT = C.CLIENTNAME
    LEFT JOIN LIST_STATUSES ON LIST_STATUSES.STATUS_NUM = O.ORDER_STATUS
    WHERE O.ORDER_STATUS > -3 
      AND O.ORDER_STATUS = 8 
      AND C.IS_PREPAID IS NULL 
      AND (O.ORDER_TOTAL_COST - COALESCE(O.ORDER_PAY, 0)) * -1 < 0
    ORDER BY O.ID DESC
  `,

  // Get all orders with debt
  getOrdersWithDebt: () => `
    SELECT DISTINCT O.ID, O.ITM_ORDERNUM, O.ORDERNUM, O.ORDER_TYPE, O.MANAGER, 
           C.CLIENTNAME, C.CITY, C.PRICE_COLUMN,
           O.FASAD_MAT, O.FASAD_MODEL, O.COLOR, O.ORDER_TOTAL_COST, O.ORDER_COST, O.ORDER_PAY,
           (O.ORDER_TOTAL_COST - COALESCE(O.ORDER_PAY, 0)) * -1 AS ORDER_DEBT, 
           O.ORDER_GENERALSQ,
           O.FACT_DATE_FIRSTSAVE, O.PLAN_DATE_FIRSTSTAGE, O.PLAN_DATE_PACK, O.FACT_DATE_ORDER_OUT,
           LIST_STATUSES.STATUS_DESCRIPTION, LIST_STATUSES.STATUS_NUM, 
           C.IS_PREPAID, O.COLOR_TYPE, O.COLOR_PATINA, O.PRIMECH
    FROM ORDERS O
    LEFT JOIN CLIENTS C ON O.CLIENT = C.CLIENTNAME
    LEFT JOIN LIST_STATUSES ON LIST_STATUSES.STATUS_NUM = O.ORDER_STATUS
    WHERE O.ORDER_STATUS > -3 
      AND (COALESCE(O.ORDER_TOTAL_COST, 0) - COALESCE(O.ORDER_PAY, 0)) * -1 < 0
    ORDER BY O.ID DESC
  `,

  // Search orders by date
  searchOrdersByDate: (date: string) => `
    SELECT DISTINCT O.ID, O.ITM_ORDERNUM, O.ORDERNUM, O.ORDER_TYPE, O.MANAGER, 
           C.CLIENTNAME, C.CITY, O.FASAD_MAT, O.FASAD_MODEL, O.COLOR, 
           O.ORDER_TOTAL_COST, O.ORDER_PAY,
           LIST_STATUSES.STATUS_DESCRIPTION, LIST_STATUSES.STATUS_NUM, C.IS_PREPAID
    FROM ORDERS O
    LEFT JOIN CLIENTS C ON O.CLIENT = C.CLIENTNAME
    LEFT JOIN LIST_STATUSES ON LIST_STATUSES.STATUS_NUM = O.ORDER_STATUS
    WHERE O.ORDER_STATUS > -3 
      AND CAST(CAST(O.FACT_DATE_FIRSTSAVE AS TIMESTAMP) AS DATE) = '${date}'
    ORDER BY O.ID DESC
  `,

  // Search orders by ID or ITM number
  searchOrdersByIdOrNumber: (searchText: string) => `
    SELECT DISTINCT O.ID, O.ITM_ORDERNUM, O.ORDERNUM, O.ORDER_TYPE, O.MANAGER, 
           C.CLIENTNAME, C.CITY, O.FASAD_MAT, O.FASAD_MODEL, O.COLOR, 
           O.ORDER_TOTAL_COST, O.ORDER_PAY,
           LIST_STATUSES.STATUS_DESCRIPTION, LIST_STATUSES.STATUS_NUM, C.IS_PREPAID
    FROM ORDERS O
    LEFT JOIN CLIENTS C ON O.CLIENT = C.CLIENTNAME
    LEFT JOIN LIST_STATUSES ON LIST_STATUSES.STATUS_NUM = O.ORDER_STATUS
    WHERE O.ORDER_STATUS > -3 
      AND (O.ID = ${searchText} OR UPPER(O.ITM_ORDERNUM) LIKE '%${searchText.toUpperCase()}%')
    ORDER BY O.ID DESC
  `,

  // Search orders by multiple keywords
  searchOrdersByKeywords: (keywords: string[]) => {
    const conditions = keywords.map(keyword => 
      `UPPER(O.ITM_ORDERNUM || COALESCE(C.CITY, '') || COALESCE(LIST_STATUSES.STATUS_DESCRIPTION, '') || 
       COALESCE(O.ORDER_TYPE, '') || COALESCE(O.MANAGER, '') || COALESCE(O.FASAD_MAT, '') || 
       COALESCE(O.FASAD_MODEL, '')) LIKE '%${keyword.replace(/,/g, '').toUpperCase()}%'`
    ).join(' AND ');

    return `
      SELECT DISTINCT O.ID, O.ITM_ORDERNUM, O.ORDERNUM, O.ORDER_TYPE, O.MANAGER, 
             C.CLIENTNAME, C.CITY, O.FASAD_MAT, O.FASAD_MODEL, O.COLOR, 
             O.ORDER_TOTAL_COST, O.ORDER_PAY,
             LIST_STATUSES.STATUS_DESCRIPTION, LIST_STATUSES.STATUS_NUM, C.IS_PREPAID
      FROM ORDERS O
      LEFT JOIN CLIENTS C ON O.CLIENT = C.CLIENTNAME
      LEFT JOIN LIST_STATUSES ON LIST_STATUSES.STATUS_NUM = O.ORDER_STATUS
      WHERE O.ORDER_STATUS > -3 AND ${conditions}
      ORDER BY O.ID DESC
    `;
  },

  // Get employee name by ITM ID
  getEmployeeName: (itmId: number) => `
    SELECT e.name 
    FROM employers e 
    WHERE e.id = ${itmId}
  `,

  // Get balance from cashbox
  getBalanceFromCashbox: () => `
    SELECT AMOUNT FROM GET_BALANSE_CASSA
  `,
};
